spring:
  application:
    name: NewProject
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
    group:
      local:
        - jpa
        - token
        - kakao
        - apple
        - metrics
  cloud:
    openfeign:
      client:
        config:
          weatherClient:
            connectTimeout: 2000   # 연결(소켓) 수립까지 최대 2초
            readTimeout: 5000      # 요청 전송 후 응답 바디 읽기까지 최대 5초

auth:
  login_success:
    base_uri: ${LOGIN_SUCCESS_BASE_URI}

weather:
  api:
    key: ${OPENWEATHER_API_KEY}
  scheduler:
    # 초 분 시 일 월 요일
    cron: 0 0 * * * *

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
    number: ${COOLSMS_SENDER_NUMBER}
