management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
