spring:
  application:
    name: NewProject
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
    group:
      local:
        - jpa
        - token
        - kakao
        - apple
        - metrics

auth:
  login_success:
    base_uri: ${LOGIN_SUCCESS_BASE_URI}